# Generated by Django 5.2.10 on 2026-01-23 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('exchange', models.CharField(blank=True, max_length=50)),
                ('asset_type', models.CharField(choices=[('EQUITY', 'Equity'), ('ETF', 'ETF')], default='EQUITY', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('open', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('provider_name', models.CharField(max_length=50)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='marketdata.instrument')),
            ],
            options={
                'indexes': [models.Index(fields=['instrument', '-as_of'], name='marketdata__instrum_df3f81_idx'), models.Index(fields=['provider_name', 'as_of'], name='marketdata__provide_0ae170_idx')],
                'constraints': [models.UniqueConstraint(fields=('instrument', 'as_of', 'provider_name'), name='uniq_quote_instrument_asof_provider')],
            },
        ),
    ]
