# Generated by Django 5.2.10 on 2026-01-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketdata", "0002_watchlistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="change",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="percent_change",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="fifty_two_week_high",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="fifty_two_week_low",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]

