# Generated by Django 5.2.10 on 2026-02-01

from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_create_default_watchlists(apps, schema_editor):
    WatchlistItem = apps.get_model("marketdata", "WatchlistItem")
    Watchlist = apps.get_model("marketdata", "Watchlist")

    # Create a default watchlist per user with at least one WatchlistItem.
    user_ids = list(
        WatchlistItem.objects.order_by()
        .values_list("user_id", flat=True)
        .distinct()
    )
    if not user_ids:
        return

    for uid in user_ids:
        wl, _ = Watchlist.objects.get_or_create(
            user_id=uid,
            name="My Watchlist",
            defaults={"industry_label": ""},
        )
        WatchlistItem.objects.filter(user_id=uid, watchlist__isnull=True).update(
            watchlist_id=wl.id
        )


def backwards_noop(apps, schema_editor):
    # No safe automatic rollback: restoring per-user items would require recreating WatchlistItem.user.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("marketdata", "0003_quote_extended_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("industry_label", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="watchlists", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("user", "name"), name="uniq_watchlist_user_name"),
                ],
                "indexes": [
                    models.Index(fields=["user", "name"], name="marketdata_wa_user_id_3b8f0a_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="watchlistitem",
            name="watchlist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="marketdata.watchlist",
            ),
        ),
        migrations.RunPython(forwards_create_default_watchlists, backwards_noop),
        # Replace uniqueness constraint: (user, instrument) -> (watchlist, instrument)
        migrations.RemoveConstraint(
            model_name="watchlistitem",
            name="uniq_watchlist_user_instrument",
        ),
        migrations.RemoveField(
            model_name="watchlistitem",
            name="user",
        ),
        migrations.AlterField(
            model_name="watchlistitem",
            name="watchlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="marketdata.watchlist",
            ),
        ),
        migrations.AddConstraint(
            model_name="watchlistitem",
            constraint=models.UniqueConstraint(
                fields=("watchlist", "instrument"),
                name="uniq_watchlist_watchlist_instrument",
            ),
        ),
    ]

