# Generated by Django 5.2.10 on 2026-02-01 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0004_multi_watchlists'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='watchlist',
            new_name='marketdata__user_id_ca325c_idx',
            old_name='marketdata_wa_user_id_3b8f0a_idx',
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='watchlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketdata.watchlist'),
        ),
    ]
