# Generated by Django 5.2.10 on 2026-01-23 03:14

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('marketdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=8)),
                ('order_type', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit')], max_length=8)),
                ('quantity', models.PositiveIntegerField()),
                ('limit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('FILLED', 'Filled'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=16)),
                ('submitted_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('quote_as_of', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='marketdata.instrument')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='competitions.competitionparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('avg_cost_basis', models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='marketdata.instrument')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='competitions.competitionparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='TradeFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('quantity', models.PositiveIntegerField()),
                ('notional', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='simulator.order')),
            ],
        ),
        migrations.CreateModel(
            name='CashLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('delta_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reason', models.CharField(choices=[('STARTING_CASH', 'Starting cash'), ('TRADE_BUY', 'Trade buy'), ('TRADE_SELL', 'Trade sell'), ('ADJUSTMENT', 'Adjustment')], max_length=24)),
                ('reference_type', models.CharField(blank=True, max_length=32)),
                ('reference_id', models.BigIntegerField(blank=True, null=True)),
                ('memo', models.TextField(blank=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_ledger_entries', to='competitions.competitionparticipant')),
            ],
            options={
                'indexes': [models.Index(fields=['participant', '-as_of'], name='simulator_c_partici_a50691_idx'), models.Index(fields=['participant', 'reference_type', 'reference_id'], name='simulator_c_partici_7b0209_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['participant', '-created_at'], name='simulator_o_partici_61d002_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['instrument', '-created_at'], name='simulator_o_instrum_62aa40_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('limit_price__isnull', True), ('order_type', 'MARKET')), models.Q(('limit_price__isnull', False), ('order_type', 'LIMIT')), _connector='OR'), name='order_limit_price_required_for_limit'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('participant', 'instrument'), name='uniq_position_participant_instrument'),
        ),
        migrations.AddIndex(
            model_name='tradefill',
            index=models.Index(fields=['-filled_at'], name='simulator_t_filled__5e2f16_idx'),
        ),
    ]
