# Generated by ChatGPT on 2026-02-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0002_tradefill_realized_pnl"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marketdata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("category", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baskets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "updated_at"], name="simulator_b_user_id_6b5cfb_idx"),
                    models.Index(fields=["user", "name"], name="simulator_b_user_id_78fba3_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BasketItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "basket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="simulator.basket",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="marketdata.instrument",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["basket", "created_at"], name="simulator_b_basket__f85bcb_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="basketitem",
            constraint=models.UniqueConstraint(
                fields=("basket", "instrument"),
                name="uniq_basketitem_basket_instrument",
            ),
        ),
    ]

