# Generated by Django 5.2.10 on 2026-02-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_baskets'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='basket',
            new_name='simulator_b_user_id_ffbe8c_idx',
            old_name='simulator_b_user_id_6b5cfb_idx',
        ),
        migrations.RenameIndex(
            model_name='basket',
            new_name='simulator_b_user_id_2e279b_idx',
            old_name='simulator_b_user_id_78fba3_idx',
        ),
        migrations.RenameIndex(
            model_name='basketitem',
            new_name='simulator_b_basket__1fe96a_idx',
            old_name='simulator_b_basket__f85bcb_idx',
        ),
    ]
