# Generated by ChatGPT on 2026-02-07

import django.db.models.deletion
from decimal import Decimal
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0006_disallow_join_after_start"),
        ("marketdata", "0001_initial"),
        ("simulator", "0004_rename_simulator_b_user_id_6b5cfb_idx_simulator_b_user_id_ffbe8c_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledBasketOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("side", models.CharField(choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=8)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("basket_name", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("EXECUTED", "Executed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_basket_orders",
                        to="competitions.competitionparticipant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["participant", "status", "created_at"],
                        name="sim_sbo_part_stat_created_idx",
                    ),
                    models.Index(fields=["status", "created_at"], name="sim_sbo_status_created_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScheduledBasketOrderLeg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pct",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            MinValueValidator(Decimal("0.01")),
                            MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="marketdata.instrument",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legs",
                        to="simulator.scheduledbasketorder",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="scheduledbasketorderleg",
            constraint=models.UniqueConstraint(
                fields=("order", "instrument"),
                name="uniq_scheduled_basket_order_leg_order_instrument",
            ),
        ),
    ]

