# Generated by Django 5.2.10 on 2026-02-07 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_scheduled_basket_orders'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scheduledbasketorder',
            new_name='simulator_s_partici_fb689b_idx',
            old_name='sim_sbo_part_stat_created_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledbasketorder',
            new_name='simulator_s_status_1ab2d3_idx',
            old_name='sim_sbo_status_created_idx',
        ),
    ]
