# Generated by Django 5.2.10 on 2026-01-23 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorprofile',
            name='attest_under_55',
        ),
    ]
