# Generated by Django 5.2.10 on 2026-01-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_investorprofile_attest_under_55'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorprofile',
            name='age_bracket',
            field=models.CharField(choices=[('18_24', '18-24'), ('25_34', '25-34'), ('35_44', '35-44'), ('45_54', '45-54'), ('55_64', '55-64'), ('65_74', '65-74'), ('75_84', '75-84'), ('85_94', '85-94'), ('95_104', '95-104')], max_length=16),
        ),
    ]
