# Generated by Django 5.2.10 on 2026-01-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_investorprofile_age_bracket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorprofile',
            name='experience_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('PRO_TRADER', 'Pro Trader')], max_length=16),
        ),
    ]
