# Generated by Django 5.2.10 on 2026-02-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminmessage',
            new_name='messaging_a_created_bd2c29_idx',
            old_name='messaging_ad_created_bf1b56_idx',
        ),
        migrations.RenameIndex(
            model_name='adminmessage',
            new_name='messaging_a_sent_at_6b6e4d_idx',
            old_name='messaging_ad_sent_at_b3a857_idx',
        ),
        migrations.RenameIndex(
            model_name='messagedelivery',
            new_name='messaging_m_user_id_23da9c_idx',
            old_name='messaging_me_user_id_2c1c0c_idx',
        ),
    ]
