# Generated by Django 5.2.10 on 2026-01-23 03:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketdata', '0001_initial'),
        ('sponsors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('week_start_at', models.DateTimeField()),
                ('week_end_at', models.DateTimeField()),
                ('theme_name', models.CharField(blank=True, max_length=200)),
                ('theme_primary_color', models.CharField(blank=True, max_length=32)),
                ('hero_image', models.FileField(blank=True, null=True, upload_to='competitions/hero/')),
                ('starting_cash', models.DecimalField(decimal_places=2, default=Decimal('1000000.00'), max_digits=20)),
                ('rules_markdown', models.TextField(blank=True)),
                ('valuation_policy', models.CharField(choices=[('LATEST_CACHED', 'Latest cached quote')], default='LATEST_CACHED', max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('LOCKED', 'Locked'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competitions', to='sponsors.sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISQUALIFIED', 'Disqualified'), ('LOCKED', 'Locked')], default='ACTIVE', max_length=16)),
                ('starting_cash', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competitions.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_symbols', to='competitions.competition')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='marketdata.instrument')),
            ],
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['status', 'week_start_at', 'week_end_at'], name='competition_status_c5b70b_idx'),
        ),
        migrations.AddConstraint(
            model_name='competitionparticipant',
            constraint=models.UniqueConstraint(fields=('competition', 'user'), name='uniq_competition_user'),
        ),
        migrations.AddConstraint(
            model_name='competitionparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('cash_balance__gte', 0)), name='participant_cash_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='competitionsymbol',
            constraint=models.UniqueConstraint(fields=('competition', 'instrument'), name='uniq_competition_instrument'),
        ),
    ]
