# Generated by Django 5.2.10 on 2026-01-23 03:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='starting_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000000.00'), max_digits=20),
        ),
    ]
