# Generated by Django 5.2.10 on 2026-01-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_alter_competition_starting_cash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompetitionSymbol',
        ),
    ]
