# Generated by Django 5.2.10 on 2026-01-31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0004_competition_entry_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="competition_type",
            field=models.CharField(
                choices=[("STANDARD", "Standard"), ("ADVANCED", "Advanced")],
                default="STANDARD",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="max_single_symbol_pct",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="competition",
            name="max_symbols",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="competition",
            name="min_symbols",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="competition",
            name="market_buy_price_source",
            field=models.CharField(
                choices=[("LAST", "Last"), ("BID", "Bid"), ("ASK", "Ask")],
                default="LAST",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="allow_sell_short",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="competition",
            name="auto_close_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="competition",
            name="auto_close_price_source",
            field=models.CharField(
                choices=[("LAST", "Last"), ("BID", "Bid"), ("ASK", "Ask")],
                default="LAST",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="synthetic_spread_bps",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Synthetic bid/ask spread in basis points (1 bp = 0.01%). Used when Bid/Ask is selected.",
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="auto_close_processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

