# Generated by ChatGPT on 2026-02-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0005_advanced_competition_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="disallow_join_after_start",
            field=models.BooleanField(default=False),
        ),
    ]

