# Generated by Django 5.2.10 on 2026-02-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_disallow_join_after_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionparticipant',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('QUEUED', 'Queued'), ('DISQUALIFIED', 'Disqualified'), ('LOCKED', 'Locked')], default='ACTIVE', max_length=16),
        ),
    ]
