# Generated by ChatGPT on 2026-02-07

from __future__ import annotations

from django.core.management.base import BaseCommand
from django.db import transaction
from django.utils import timezone

from competitions.models import (
    Competition,
    CompetitionParticipant,
    CompetitionStatus,
    ParticipantStatus,
)
from simulator.models import CashLedgerEntry, CashLedgerReason


class Command(BaseCommand):
    help = "Activate QUEUED participants for competitions that have started (cron-friendly)."

    def handle(self, *args, **options):
        now = timezone.now()

        competitions = list(
            Competition.objects.filter(
                status=CompetitionStatus.PUBLISHED,
                week_start_at__lte=now,
                week_end_at__gte=now,
            ).only("id", "starting_cash")
        )
        if not competitions:
            self.stdout.write("No active competitions found.")
            return

        competition_ids = [c.id for c in competitions]

        activated = 0
        with transaction.atomic():
            queued = list(
                CompetitionParticipant.objects.select_for_update()
                .select_related("competition")
                .filter(competition_id__in=competition_ids, status=ParticipantStatus.QUEUED)
                .order_by("id")
            )
            for p in queued:
                # Idempotency: only activate QUEUED rows.
                if p.status != ParticipantStatus.QUEUED:
                    continue
                # Credit starting cash on activation.
                p.cash_balance = p.starting_cash
                p.status = ParticipantStatus.ACTIVE
                p.save(update_fields=["cash_balance", "status", "updated_at"])

                CashLedgerEntry.objects.create(
                    participant=p,
                    delta_amount=p.starting_cash,
                    reason=CashLedgerReason.STARTING_CASH,
                    reference_type="COMPETITION",
                    reference_id=p.competition_id,
                    memo="Queued participant activated at competition start.",
                )
                activated += 1

        self.stdout.write(f"Activated {activated} queued participant(s).")

