# Generated by Django 5.2.10 on 2026-01-23 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateTimeField()),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('holdings_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('return_pct_since_start', models.DecimalField(decimal_places=6, max_digits=12)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to='competitions.competitionparticipant')),
            ],
            options={
                'indexes': [models.Index(fields=['-as_of'], name='leaderboard_as_of_f33683_idx'), models.Index(fields=['participant', '-as_of'], name='leaderboard_partici_d76ce3_idx')],
            },
        ),
    ]
