# Generated by Cursor on 2026-01-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfoliosnapshot",
            name="realized_pnl_today",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="portfoliosnapshot",
            name="realized_pnl_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="portfoliosnapshot",
            name="unrealized_pnl",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]

